### ISSUE TITLE
Time in UTC is calculated wrongly

### ISSUE THREAD

**Issue by amosngSP** [e4rthdog/VatBoard.Web#3]
Hi,

I noticed that the time in UTC goes beyond 24 hours (at the time when i typed this, its showing 30:28 UTC).

Gave the code a quick check, in your function showTime, you should use `date.getUTCHours` instead. This shows the UTC time directly without the need to manipulate the value. The same modifications should be done to the minutes and seconds function. :).

This is overall a great website! Keep the good work going! :).
![Screenshot_20210927-023323_Chrome](https://user-images.githubusercontent.com/40349656/134819852-c41c482f-3d25-4d4a-b8a3-7c35da2db88b.jpg)

**Comment by e4rthdog** [comment]
OOps!! Thanks man, i will take care of it during the day.

**Comment by e4rthdog** [comment]
We should be ok now. Thanks.
