### ISSUE TITLE
The website didnt work

### ISSUE THREAD

**Issue by deedee2110** [e4rthdog/VatBoard.Web#4]
http://www.estassinos.com/vatboard-web is not available

**Comment by deedee2110** [comment]
![image](https://user-images.githubusercontent.com/68428658/166435667-2c586755-1231-4faf-a39b-60c9a7008c98.png)

**Comment by e4rthdog** [comment]
mmm there is something with the generated links....
[image: image.png]

remove the extra estassinos-com/www and it will work

i will take a look at it.

*Elias Stassinos*

**Comment by deedee2110** [comment]
Okay If i removed it.It keep going back to the same link

**Comment by e4rthdog** [comment]
Try adding manually https:// in the beggining..

*Elias Stassinos*

**Comment by deedee2110** [comment]
It works Thanks so much :)
https://www.estassinos.com/vatboard-web/
